# Generated by Django 5.0.4 on 2024-04-20 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='toDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=100)),
                ('todo_description', models.CharField(blank=True, max_length=250, null=True)),
                ('todo_created_on', models.DateField(default=datetime.datetime.today)),
                ('todo_modified_on', models.DateField(default=datetime.datetime.today)),
                ('todo_is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
