# Generated by Django 5.0.4 on 2024-04-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='todo_modified_on',
            field=models.DateField(auto_now=True),
        ),
    ]
